[package]
name = "build_utils"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.89"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"

[lib]
path = "src/lib.rs"
